version: "3.7"

services:
  postgres:
    container_name: vogetio-db
    image: postgres:12-alpine
    restart: always
    command: ["-c", "statement_timeout=60000"]
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: vogetio
      POSTGRES_USER: vogetio
      POSTGRES_PASSWORD: vogetio
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - internal

  migrate-db:
    container_name: migrate-db
    image: node:14-alpine
    depends_on:
      - postgres
    restart: "no"
    volumes:
      - ./db:/home/node/db
    working_dir: /home/node/db
    command: /bin/sh -c 'DATABASE_URL="postgresql://vogetio:vogetio@postgres:5432/vogetio?schema=public" npm run migrate'
    networks:
      - internal

  app:
    container_name: vogetio-app
    image: node:14-alpine
    volumes:
      - ./app:/home/node/app
    working_dir: /home/node/app
    command: /bin/sh -c "npm run dev"
    ports:
      - 3000:3000
    networks:
      - internal

  server:
    container_name: vogetio-server
    image: node:14-alpine
    volumes:
      - ./server:/home/node/server
    command: /bin/sh -c "npm run dev"
    working_dir: /home/node/server
    ports:
      - 3001:3001
    environment:
      DATABASE_URL: "postgresql://vogetio:vogetio@postgres:5432/vogetio?schema=public"
    networks:
      - internal

networks:
  internal:

volumes:
  postgres:
