version: 2.1

orbs:
  node: circleci/node@4.7.0

commands:
  gcloud-install:
    description: Installs and Configures Google Cloud SDK
    steps:
      - run:
          name: Install and Configure Google Cloud SDK
          command: |
            # install Google Cloud SDK distribution
            curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-365.0.1-linux-x86.tar.gz
            tar xvfz google-cloud-sdk-365.0.1-linux-x86.tar.gz
            CLOUDSDK_CORE_DISABLE_PROMPTS=1 ./google-cloud-sdk/install.sh
            export PATH=$PATH:$(pwd)/google-cloud-sdk/bin
            echo "export PATH=$PATH:$(pwd)/google-cloud-sdk/bin" >> ~/.bashrc && source ~/.bashrc

            gcloud components install docker-credential-gcr

            # activate the GCP service acct
            unzip -P $GCP_DECRYPTION_PASSWORD .circleci/gcp-svc-acct.zip
            gcloud auth activate-service-account --key-file=kinetic-object-322814-7a336f8de0fa.json --project=kinetic-object-322814
            docker-credential-gcr configure-docker
            gcloud -q auth configure-docker

  docker-build-and-push:
    parameters:
      component-name:
        type: string
        description: Name of the component to build and push
    steps:
      - run:
          name: "Build and Tag Image"
          command: |
            cd <<parameters.component-name>>
            docker build -t gcr.io/kinetic-object-322814/vogetio-<<parameters.component-name>> -f Dockerfile .
      - run:
          name: "Push Image to GCR"
          command: |
            docker push gcr.io/kinetic-object-322814/vogetio-<<parameters.component-name>>

jobs:
  build-and-push:
    parameters:
      component-name:
        type: string
        description: Name of the component to build and push
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout
      - node/install
      - gcloud-install
      - docker-build-and-push:
          component-name: <<parameters.component-name>>

workflows:
  default:
    jobs:
      - build-and-push:
          name: build-and-push-app
          component-name: app
          filters:
            branches:
              only:
                - master
      - build-and-push:
          name: build-and-push-server
          component-name: server
          filters:
            branches:
              only:
                - master
