version: 2.1

orbs:
  node: circleci/node@4.7.0

commands:
  docker-build-and-push:
    parameters:
      component-name:
        type: string
        description: Name of the component to build and push
    steps:
      - run:
          name: "Build Image"
          command: |
            cd <<parameters.component-name>>
            docker build -t vogetio-<<parameters.component-name>>:latest -f Dockerfile .
      - run:
          name: "Tage and Push Image to GCR"
          command: |
            docker tag vogetio-<<parameters.component-name>>:latest gcr.io/kinetic-object-322814/vogetio-<<parameters.component-name>>
            docker push gcr.io/kinetic-object-322814/vogetio-<<parameters.component-name>>

jobs:
  build-and-push:
    parameters:
      component-name:
        type: string
        description: Name of the component to build and push
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout
      - node/install
      - docker-build-and-push:
          component-name: <<parameters.component-name>>

workflows:
  default:
    jobs:
      - build-and-push:
          name: build-and-push-app
          component-name: app
          filters:
            branches:
              only:
                - master
      - build-and-push:
          name: build-and-push-server
          component-name: server
          filters:
            branches:
              only:
                - master
