version: 2.1

orbs:
  node: circleci/node@4.7.0

commands:
  gcloud-auth:
    description: Authenticates with Google Cloud SDK
    steps:
      - run:
          name: Authenticate with Google Cloud SDK
          command: |
            apt-get update && apt-get install -y unzip
            unzip -P $GCP_DECRYPTION_PASSWORD .circleci/gcp-svc-acct.zip
            gcloud auth activate-service-account --key-file=kinetic-object-322814-7a336f8de0fa.json --project=kinetic-object-322814
            gcloud -q auth configure-docker

  check-for-changes:
    description: Check for changes in the given component
    parameters:
      component:
        type: string
        description: The name of the component to check for changes in
    steps:
      - run:
          name: "Detect code changes"
          command: |
            changes=$(git diff --name-only HEAD^ HEAD | sed -n /<<parameters.component>>/p | wc -l | xargs)
            if [ "$changes" = "0" ]; then
              echo "Detected no changes to the <<parameters.component>> code"
              circleci-agent step halt
            fi

jobs:
  build-and-deploy-blog-service:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - check-for-changes:
          component: blog-service
      - gcloud-auth
      - node/install
      - run:
          name: "Build and Deploy blog-service"
          command: |
            cd blog-service

            # build the blog-service
            npm ci --silent
            npm run build

            # cloud function deploy
            ./deploy-cloud-function.sh

  build-and-deploy-app:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - check-for-changes:
          component: app
      - gcloud-auth
      - node/install
      - run:
          name: "Build and Deploy vogetio-app"
          command: |
            cd app

            # Webpack build
            npm install webpack@5.64.4 -g
            npm ci --silent
            BLOG_SERVICE_URL=$BLOG_SERVICE_URL && npm run webpack

            # Upload to bucket
            gsutil cp -r dist/* gs://vogetio-app/

workflows:
  default:
    jobs:
      - build-and-deploy-app:
          filters:
            branches:
              only:
                - master
      - build-and-deploy-blog-service:
          filters:
            branches:
              only:
                - master
