version: 2.1

commands:
  gcloud-auth:
    description: Authenticates with Google Cloud SDK
    steps:
      - run:
          name: Authenticate with Google Cloud SDK
          command: |
            apt-get update && apt-get install -y unzip
            unzip -P $GCP_DECRYPTION_PASSWORD .circleci/gcp-svc-acct.zip
            gcloud auth activate-service-account --key-file=kinetic-object-322814-7a336f8de0fa.json --project=kinetic-object-322814
            gcloud -q auth configure-docker

  docker-build-and-push:
    parameters:
      component-name:
        type: string
        description: Name of the component to build and push
    steps:
      - run:
          name: "Build and Push Image"
          command: |
            GIT_COMMIT="$(git rev-parse --short HEAD)"
            cd <<parameters.component-name>>
            docker build -t gcr.io/kinetic-object-322814/vogetio-<<parameters.component-name>>:$GIT_COMMIT -f Dockerfile .
            docker push gcr.io/kinetic-object-322814/vogetio-<<parameters.component-name>>:$GIT_COMMIT

jobs:
  build-and-push:
    parameters:
      component-name:
        type: string
        description: Name of the component to push to GCR
    docker:
      - image: google/cloud-sdk
    steps:
      - setup_remote_docker
      - checkout
      - gcloud-auth
      - docker-build-and-push:
          component-name: <<parameters.component-name>>

  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - gcloud-auth
      - run:
          name: Deploy with helm
          command: |
            # install kubectl
            apt-get install -y kubectl

            gcloud container clusters get-credentials vogetio-cluster --zone us-central1 --project kinetic-object-322814
            kubectl config set-context --current --namespace=default

            # install helm
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

            GIT_COMMIT="$(git rev-parse --short HEAD)"

            cd deploy/vogetio-cluster

            helm upgrade prod . --set imageTag=$GIT_COMMIT --wait --debug

workflows:
  default:
    jobs:
      # - build-and-push:
      #     name: build-and-push-app
      #     component-name: app
      #     filters:
      #       branches:
      #         only:
      #           - master
      # - build-and-push:
      #     name: build-and-push-server
      #     component-name: server
      #     filters:
      #       branches:
      #         only:
      #           - master
      - deploy:
          filters:
            branches:
              only:
                - master
