version: 2.1

orbs:
  node: circleci/node@4.7.0

commands:
  gcloud-auth:
    description: Authenticates with Google Cloud SDK
    steps:
      - run:
          name: Authenticate with Google Cloud SDK
          command: |
            apt-get update && apt-get install -y unzip
            unzip -P $GCP_DECRYPTION_PASSWORD .circleci/gcp-svc-acct.zip
            gcloud auth activate-service-account --key-file=kinetic-object-322814-7a336f8de0fa.json --project=kinetic-object-322814
            gcloud -q auth configure-docker

  check-for-changes:
    description: Check for changes in the given component
    parameters:
      component:
        type: string
        description: The name of the component to check for changes in
    steps:
      - run:
        name: "Detect code changes"
        command: |
          changes=$(git diff --name-only HEAD^ HEAD | sed -n /<<parameters.component>>/p | wc -l | xargs)
          if [ "$changes" = "0" ]; then
            echo "Detected no changes to the <<parameters.component>> code"
            exit 0
          fi

jobs:
  migrate-db:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - check-for-changes:
          component: db
      - node/install
      - run:
          name: "Apply migrations to the database"
          command: |
            cd db
            npm install
            DATABASE_URL=$DB_URL npm run migrate

  build-and-deploy-server:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - check-for-changes:
          component: server
      - setup_remote_docker
      - gcloud-auth
      - run:
          name: "Build and Deploy vogetio-server"
          command: |
            GIT_COMMIT="$(git rev-parse --short HEAD)"
            cd server
            docker build -t gcr.io/kinetic-object-322814/vogetio-server:$GIT_COMMIT -f Dockerfile .
            docker push gcr.io/kinetic-object-322814/vogetio-server:$GIT_COMMIT

            gcloud run deploy vogetio-server --image=gcr.io/kinetic-object-322814/vogetio-server:$GIT_COMMIT --project=kinetic-object-322814 --region=us-central1

  build-and-deploy-app:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - check-for-changes:
          component: app
      - gcloud-auth
      - node/install
      - run:
          name: "Build and Deploy vogetio-app"
          command: |
            cd app

            # Webpack build
            npm install webpack@5.64.4 -g
            npm ci --silent
            npm run build-prod $SERVER_URL

            # Upload to bucket
            gsutil cp -r dist/* gs://vogetio-app/

workflows:
  default:
    jobs:
      - migrate-db:
          filters:
            branches:
              only:
                - master
      - build-and-deploy-server:
          filters:
            branches:
              only:
                - master
      - build-and-deploy-app:
          filters:
            branches:
              only:
                - master
