apiVersion: apps/v1
kind: Deployment
metadata:
  name: vogetio-app
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: vogetio-app-deployment-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/component: vogetio-app-deployment-pod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/component: vogetio-app-deployment-pod
    spec:
      containers:
        - name: vogetio-app
          image: gcr.io/kinetic-object-322814/vogetio-app:{{ .Values.imageTag }}
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /_health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /_health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              memory: 100M
