apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: vogetio-address
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: vogetio-app
      port:
        number: 3000
