apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |

    upstream vogetio-app {
      server vogetio-app:3000;
    }

    upstream vogetio-server {
      server vogetio-server:3001;
    }

    server {
      listen 8080 default_server;
      listen [::]:8080 default_server;

      # Frontend
      location / {
        proxy_pass http://vogetio-app; # same name as network alias
      }

      # Backend
      location /api {
        proxy_pass http://vogetio-server;  # <--- note this has an extra /
      }

      # You may need this to prevent return 404 recursion.
      location = /404.html {
        internal;
      }

      location = /_health {
        gzip on;
        gzip_types * ;

        return 200 "OK";
      }
    }
