apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: nginx-service
spec:
  ports:
    - name: nginx
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: nginx-deployment-pod
  sessionAffinity: None
  type: NodePort
